# DS
Movie.destroy_all

shawshank = Movie.create!(title: "The Shawshank Redemption", gross: 25000000, release: Date.new(1994, 10, 14), rating: "R", description: "Andy Dufresne is a young and successful banker whose life changes drastically when he is convicted and sentenced to life imprisonment for the murder of his wife and her lover. Set in the 1940's, the film shows how Andy, with the help of his friend Red, the prison entrepreneur, turns out to be a most unconventional prisoner.")
godfather = Movie.create!(title: "The Godfather", gross: 134821952, release: Date.new(1972, 3, 24), rating: "R", description: "When the aging head of a famous crime family decides to transfer his position to one of his subalterns, a series of unfortunate events start happening to the family, and a war begins between all the well-known families leading to insolence, deportation, murder and revenge, and ends with the favorable successor being finally chosen.")
godfather2 = Movie.create!(title: "The Godfather: Part II", gross: 57300000, release: Date.new(1974, 12, 20), rating: "R", description: "The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.")
dark_knight = Movie.create!(title: "The Dark Knight", gross: 533316061, release: Date.new(2008, 7, 18), rating: "PG-13", description: "Batman raises the stakes in his war on crime. With the help of Lieutenant Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the city streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as The Joker.")
pulp_fiction = Movie.create!(title: "Pulp Fiction", gross: 107928762, release: Date.new(1994, 10, 14), rating: "R", description: "Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.")
shawshank.reviews << Review.create!(comment: "I have never seen such an amazing film since I saw The Shawshank Redemption. Shawshank encompasses friendships, hardships, hopes, and dreams. And what is so great about the movie is that it moves you, it gives you hope. Even though the circumstances between the characters and the viewers are quite different, you don't feel that far removed from what the characters are going through.

It is a simple film, yet it has an everlasting message. Frank Darabont didn't need to put any kind of outlandish special effects to get us to love this film, the narration and the acting does that for him. Why this movie didn't win all seven Oscars is beyond me, but don't let that sway you to not see this film, let its ranking on the IMDb's top 250 list sway you, let your friends recommendation about the movie sway you.

Set aside a little over two hours tonight and rent this movie. You will finally understand what everyone is talking about and you will understand why this is my all time favorite movie.", stars: 5, reviewer: "speedreid")
godfather.reviews << Review.create!(comment: "This movie is strong, good script, great casting, excellent acting, and over the top directing. It is hard to fine a movie done this well, it is 29 years old and has aged well. Even if the viewer does not like mafia type of movies, he or she will watch the entire film, the audiences is glued to what will happen next as the film progresses. Its about, family, loyalty, greed, relationships, and real life. This is a great mix, and the artistic style make the film memorable.", stars: 5, reviewer: "mm-39")
godfather2.reviews << Review.create!(comment: "This movie is way to be good to be labelled a sequel to The Godfather . Rather it is more of a companion piece to the original and the two perfectly compliment each other . IT is both a sequel and prequel showing the rise of the young vito and moral decline of Micheal . Both characters are brought to life with uncanny ability by Robert DeNiro and Al Pacino . To say that these two are good actors is like saying that a nuclear bomb makes a loud noise and in this movie they prove why they are at the top of their respective crafts .

Al Pacino is the standout in the ensemble cast and its amazing how his eyes have changed from the first part . They are now cold , ruthless and unemotional and betray the price which Micheal Corleone has paid for power .

Watch this movie and learn why it is the greatest gangster film of all time.", stars: 5, reviewer: "taimur74")
dark_knight.reviews << Review.create!(comment: 'I had the honor of watching TDK during a screening and was completely blown away! This isn\'t just the best Batman movie ever made, this is one of the best movie ever made. Everything in this film is excellent, not one piece of annoyance.

Bale marvels as Bruce Wayne/Batman, Ledger has made The Joker in to an iconic movie villain. His performance belongs there at the top with Hopkins Lecter. The Joker has finally been portrait properly on film, he has earned his place between the big boys in movie villandom. This is the true Joker every Batman fan knows, loves and fears. Ledger deserves any and every movie award known to man for this brilliant display.

Nolan has made his "I will always be remembered" movie, this is the crownjewel in his portfolio. Perfect directing, perfect story, perfect balance between action and drama, everything is perfect.

Even if you hate Batman, you will love this film. If you don\'t, then something beez wrongz with youz!', stars: 5, reviewer: "manuel_de_dios")
pulp_fiction.reviews << Review.create!(comment: 'If you think "Pulp Fiction" is brilliant, you\'re wrong. It\'s more than that. It\'s a milestone in the history of film making. It\'s already a classic. But why? Because of the many "f" words, or maybe because of the brain and skull pieces on the rear window of a car? No, that\'s surely not the point (unfortunately some other users - fortunately the minority - don\'t get it). Tarantino has made a movie that\'s someway different from many other action, gangster or crime movies. What\'s so different? He knows the subject of the movie is "cool", he knows it\'s a product of mass culture, and he even likes it by himself. But he smiles at it and tells three great stories with a lot of irony. And this irony is the first point. The second point is that he gave souls to extremely schematic characters. They surely aren\'t another action heroes who you forget as fast as you can twinkle. They are human beings like we are, talking about Burger King and McDonalds, about TV series and a foot massage. They just earn their money with killing others or selling drugs. What else is so great about "Pulp Fiction"? It\'s the acting, the directing, the cinematography, the soundtrack, the sense of humour and the whole rest. In my opinion it\'s all worth nothing less than a 10 out of 10. A masterpiece.', stars: 5, reviewer: "Luke-20")
pulp_fiction.reviews << Review.create!(comment: "To put this in context, I am 34 years old and I have to say that this is the best film I have seen without doubt and I don't expect it will be beaten as far as I am concerned. Obviously times move on, and I acknowledge that due to its violence and one particularly uncomfortable scene this film is not for everyone, but I still remember watching it for the first time, and it blew me away. Anyone who watches it now has to remember that it actually changed the history of cinema. In context- it followed a decade or more of action films that always ended with a chase sequence where the hero saved the day - you could have written those films yourself. Pulp had you gripped and credited the audience with intelligence. There is not a line of wasted dialogue and the movie incorporates a number of complexities that are not immediately obvious. It also resurrected the career of Grease icon John Travolta and highlighted the acting talent of Samuel L Jackson. There are many films now that are edited out of sequence and have multiple plots etc but this is the one they all want to be, or all want to beat, but never will.", stars: 5, reviewer: "wolvesrug")
